### ISSUE TITLE
Can't install Vim

### ISSUE THREAD

**Issue by jdmichaud** [buildroot/buildroot#13]
Vim says wchar is necessary. But when you activate WCHAR in the toolchain menu, you can't install Vim.
It think the problem comes from the `package/vim/Config.in` file:
```
config BR2_PACKAGE_VIM
        bool "vim"
        depends on BR2_USE_MMU # uses fork()
        depends on BR2_USE_WCHAR
[...]
comment "vim needs a toolchain w/ wchar"
        depends on !BR2_USE_WCHAR
        depends on BR2_USE_MMU
```

Shouldn't it be:
```
comment "vim needs a toolchain w/ wchar"
        depends on !BR2_USE_WCHAR
        depends on !BR2_USE_MMU
```

**Comment by lucaceresoli** [comment]
Thanks for the report. However, as explained on the Buildroot Github page, this is not where the Buildroot development takes place. Could you report your bug to the Buildroot bug tracker, or to the Buildroot mailing list? Also please detail which architecture you're using, it might be related to your issue.

**Comment by tpetazzoni** [comment]
As Luca indeed said, we don't take issues on Github. However, the code you're pointing at looks perfectly correct. The intent is that:

1. The BR2_PACKAGE_VIM option should be visible only if you have WCHAR support *and* if your CPU has a MMU
1. The comment about vim requiring wchar support toolchain should be visible only if your CPU has a MMU *and* if your toolchain doesn't have WCHAR support. Indeed, it is completely useless to tell the user "please enable WCHAR support in your toolchain to be enable to enable vim" if the CPU doesn't have a MMU: after enabling WCHAR, the user would still not be able to enable vim.

So this part looks perfectly correct, and your problem is elsewhere. Please make a complete bug report in the Buildroot bug tracker, including your Buildroot .config file, as well as the last ~100 lines of the build output. Also make sure that the problem you're seeing occurs after a complete rebuild, i.e after doing "make clean all". Please read https://buildroot.org/downloads/manual/manual.html#full-rebuild for details.
