### ISSUE TITLE
Dumb question

### ISSUE THREAD

**Issue by MrAda** [buildroot/buildroot#19]
Today 7/17/16 I created a ZIP file of the state of the clone's software and found that I couldn't get past this point:
ERROR: No hash found for gcc-4.9.3.tar.bz2

Don't people check to make sure that everything at least builds/compiles before changing the baseline?  It worked a couple of days ago and I am seriously getting frustrated.

**Comment by tpetazzoni** [comment]
Please do not use the Github issue tracker for Buildroot issues: use the Buildroot mailing list, IRC channel or bug tracker.

In your bug report, please specify the exact Buildroot version  you're using (the Git commit ID if you're not using a release tarball) and the Buildroot configuration you're using. I just checked, and the latest Git version does have the hash for gcc 4.9.3, and it has not changed since June 2015, when gcc 4.9.3 support was introduced as a replacement of gcc 4.9.2.

**Comment by MrAda** [comment]
@tpetazzoni the reason I used this site is because this was the only one I could download from.  I am using a tarball.  Now that the main site is up, I'll try downloading again.
